In [1]:
pip install gym

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 17.9 MB/s eta 0:00:00 MB/s eta 0:00:01
  Preparing metadata (setup.py) ... done
  Created wheel for gym: filename=gym-0.21.0-py3-none-any.whl size=1616825 sha256=d4bfbd8f57a34ed0743ddcd9a4703912c50a7b72c3146fbc6399c324cee6cdde
  Stored in directory: /home/abhishekjaiswal/.cache/pip/wheels/b3/50/6c/0a82c1358b4da2dbd9c1bb17e0f89467db32812ab236dbf6d5
Successfully built gym
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v1")

In [4]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
num_episodes = 10000
max_steps_per_episode = 100
learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [6]:
rewards_all_episodes = []

# Q-Learning Algorithm
for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        # Exploration-Exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        # Update Q-Table for Q(s,a)
        q_table[state,action] = (q_table[state,action] * (1 - learning_rate)) + (learning_rate * (reward + discount_rate * np.max(q_table[new_state,:])))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
                        
    # Exploration Decay Rate
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
                                                                                            
    rewards_all_episodes.append(rewards_current_episode)
            
# Calculate and print the average rewards per thousand episodes
rewards_per_thousand_episodes = np.array_split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000
print("********Average Reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count,': ',str(sum(r/1000)))
    count += 1000
                    
# Printing updated Q-Table
print("********Q-Table********\n")
print(q_table)

********Average Reward per thousand episodes********

1000 :  0.05000000000000004
2000 :  0.20900000000000016
3000 :  0.3960000000000003
4000 :  0.5500000000000004
5000 :  0.6150000000000004
6000 :  0.6800000000000005
7000 :  0.6780000000000005
8000 :  0.6650000000000005
9000 :  0.7020000000000005
10000 :  0.6790000000000005
********Q-Table********

[[0.56220327 0.51760578 0.5276612  0.52682229]
 [0.34298173 0.21619112 0.350872   0.53019442]
 [0.41181769 0.4142003  0.38570786 0.49801625]
 [0.30203851 0.34302832 0.3259986  0.47814163]
 [0.57714589 0.36886091 0.22958912 0.38869071]
 [0.         0.         0.         0.        ]
 [0.19703262 0.17639466 0.35146193 0.15864807]
 [0.         0.         0.         0.        ]
 [0.27045181 0.46173515 0.3435569  0.61769293]
 [0.34495425 0.65898474 0.5387514  0.42350831]
 [0.69928433 0.40395618 0.38614135 0.29578518]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.44920842 0.62086753 0.73825128 0.

In [7]:
for episode in range(3):
    state = env.reset()
    done = False
    print("********EPISODE ",episode+1,"********\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("******You Reached the goal******")
                time.sleep(3)
            else:
                print("******You fell through a Hole******")
                time.sleep(3)
            clear_output(wait=True)
            break
            
            
        state = new_state

env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
******You Reached the goal******
